version: '3.8'
services:
  backend:
    image: services:v1
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python /src/main/core/main.py'
    ports:
      - 5000:5000
    volumes:
      - .:/src/main
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306