version: '3.8'
services:
  backend:
    image: services:v1             # Name:Tag
    build:
      context: .
      dockerfile: Dockerfile
    command: 'gunicorn --bind 0.0.0.0:5000 runner:app'
    expose:
      - 5000                       # Expose Port 5000 Externally
    volumes:
      - .:/src/main                # Map current base DIR to DIR inside container
    env_file:
      - ./.env.dev.v1                 # Environment Variable
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always                # Restart Container
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      COMPOSE_CONVERT_WINDOWS_PATHS: 1
    volumes:
      - .dbdata:/var/lib/mysql     # Persistent Storage
    ports:
      - 33067:3306

  nginx:
    build: ./web_server/nginx      # Nginx DockerFile and Config - Web Server
    ports:
      - 80:80                      # External Port: Internal Nginx Port
    depends_on:
      - backend