apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: services-vs
spec:
  hosts:
  - "*" # mydemo.info
  gateways:
  - services-gateway
  http:
  - route:
    - destination:
        host: services-app-service
      weight: 50
    - destination:
        host: services-app-service-v2
      weight: 50
