apiVersion: apps/v1
kind: Deployment
metadata:
  name: services-app-v3
  labels:
    app: services-app-v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: services-app-v3
  template:
    metadata:
      labels:
        app: services-app-v3
    spec:
      containers:
      - name: services-app-v3
        image: rakeshram909/services:v3
        command: ["gunicorn", "--bind", "0.0.0.0:5000", "runner:app"]
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: VER
          value: "V3"
        - name: RT
          value: "Y"
---
apiVersion: v1
kind: Service
metadata:
  name: services-app-service-v3
  labels:
    app: services-app-service-v3
spec:
  selector:
    app: services-app-v3
  type: ClusterIP             # LoadBalancer OR ClusterIP(Default) OR NodePort
  ports:
    - protocol: TCP
      port: 5000              # External connection
      targetPort: 5000        # Internal POD connection
      name: http-app