apiVersion: apps/v1
kind: Deployment
metadata:
  name: services-app
  labels:
    app: services-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: services-app
  template:
    metadata:
      labels:
        app: services-app
    spec:
      containers:
      - name: services-app
        image: rakeshram909/services:v1
        command: ["gunicorn", "--bind", "0.0.0.0:5000", "runner:app"]
        imagePullPolicy: Always
        ports:
        - containerPort: 5000