apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: services-retry
spec:
  hosts:
  - mydemo.info
  gateways:
  - services-gateway
  http:
  - route:
    - destination:
        host: services-app-service-v3
    retries:
      attempts: 10
      perTryTimeout: 2s