apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: services-retry
spec:
  hosts:
  - mydemo.info
  gateways:
  - services-gateway
  http:
  - route:
    - destination:
        host: services-app-service-v3
    timeout: 8s            # Circuit Breaker
    retries:               # https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRetry
      attempts: 5          # Attempt 5 times
      perTryTimeout: 3s    # Attempt is marked as failed if it takes longer than 3 seconds
      retryOn: 5xx         # https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-retry-on