apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: services-canary
spec:
  hosts:
  - mydemo.info
  gateways:
  - services-gateway
  http:
  - match:
    - uri:
        prefix: /
      headers:
        cookie:
          regex: ^(.*?;)?(ver=v2)(;.*)?$     # Redirect to V2 when cookie is set as ver=v2
    route:
    - destination:
        host: services-app-service-v2
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: services-app-service           # Default Service