apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-app-v1
  labels:
    app: email-app-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-app-v1
  template:
    metadata:
      labels:
        app: email-app-v1
    spec:
      containers:
      - name: email-app-v1
        image: rakeshram909/email_svc:v1
        command: ["gunicorn", "--bind", "0.0.0.0:5000", "runner:app"]
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: email-app-svc-v1
  labels:
    app: email-app-svc-v1
spec:
  selector:
    app: email-app-v1
  type: ClusterIP             # LoadBalancer OR ClusterIP(Default) OR NodePort
  ports:
    - protocol: TCP
      port: 5000              # External connection
      targetPort: 5000        # Internal POD connection
      name: http-app
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: email-vs
spec:
  hosts:
  - mydemo.info
  gateways:
  - services-gateway
  http:
  - match:
    - uri:
        prefix: /email_svc               # Prefix URL
    route:
    - destination:
        host: email-app-svc-v1           # Email Service