apiVersion: v1
kind: Service
metadata:
  name: services-app-service
spec:
  selector:
    app: services-app
  type: NodePort             # LoadBalancer OR ClusterIP(Default) OR NodePort
  ports:
    - protocol: TCP
      port: 5000              # External connection
      targetPort: 5000        # Internal POD connection